# Generated by Django 3.2 on 2022-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='books',
        ),
        migrations.AddField(
            model_name='collection',
            name='books',
            field=models.ManyToManyField(to='collection.Book'),
        ),
    ]
