# Generated by Django 3.2 on 2022-05-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20220527_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
