# Generated by Django 3.2 on 2022-05-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_delete_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name', 'year']},
        ),
    ]
